extends: habitat_r2r.yaml
environment:
  params:
    native_factory_params:
      config_path: config/envs/habitat/r2r_dualvln.yaml
    native_actions:
      stand_still: null
    camera:
      pitch_deg: -30
provenance:
  sensor_profile: dualvln-look-down-30deg
