environment:
    factory: envs.ai2thor:RoboTHOREnvironment
    params:
      controller_kwargs:
        commit_id: bad5bc2b250615cb766ffb45d455c211329af17e
        width: 640
        height: 480
        rotateStepDegrees: 30
        visibilityDistance: 1.0
        gridSize: 0.25
        agentType: stochastic
        continuousMode: true
        snapToGrid: false
        agentMode: locobot
        fieldOfView: 63.453048374758716
        renderDepthImage: true
      max_actions: 500
      render_depth: true
      expose_pose: false
      expose_action_feedback: false
provenance:
  simulator: AI2-THOR 2.7.2
  simulator_build: bad5bc2b250615cb766ffb45d455c211329af17e
