# @package _global_

defaults:
  - /benchmark/nav/objectnav/objectnav_mp3d
  - _self_

habitat:
  dataset:
    split: val
    data_path: data/datasets/objectnav/mp3d/v1/{split}/{split}.json.gz
    scenes_dir: data/scene_datasets
