benchmark:
  factory: benches.robothor_objectnav:RoboTHORObjectNavBenchmark
  params:
    root: data/datasets/robothor-objectnav-2021
    split: val
provenance:
  benchmark: RoboTHOR ObjectNav 2021
  dataset_commit: f3c4f35bc397aff4d5236e269efe3ff41f6d218e
